### ISSUE TITLE
Changing Baud Rate

### ISSUE THREAD

**Issue by gokhangocmen94** [anotherlab/UsbSerialForAndroid#1]
Hello,
I want to change Baud Rate in this project.

For example
Write("character");//in 300 Baud Rate
Read();
Write("character");//in 1200 Baud Rate
Read();

How Can I do this?
Help me please

**Comment by anotherlab** [comment]
The sample app has code for opening the port with the initial properties.  Take a look at [SerialConsoleActivity.cs](https://github.com/anotherlab/UsbSerialForAndroid/blob/master/UsbSerialExampleApp/SerialConsoleActivity.cs)

If you are using the CdcAcmSerialDriver, you can use the SetParameters() method to set the serial port parameters after it has been opened.

**Comment by gokhangocmen94** [comment]
`private void SleepButton_Click(object sender, EventArgs e)
        {
            byte[] flagData = new byte[] { 0x35, 0x36, 0x35, 0x36, 0x35 }; //This is example data.
            WriteData(flagData);//I can see successfully

        }`
`private void WakeButton_Click(object sender, EventArgs e)
        {
            byte[] ackData = new byte[] { 0x30, 0x31, 0x32, 0x33, 0x34 };
            serialIoManager.BaudRate = 1200;
            serialIoManager.DataBits = 7;
            serialIoManager.StopBits = StopBits.One;
            serialIoManager.Parity = Parity.Even;
            WriteData(flagData);//I can't see successfully
        }`
My device is FT232RL. How Can I Change Baud Rate?

**Comment by anotherlab** [comment]
What happens when you set the baud rate using the SetParameters() method? Take a look at the code in [SerialInputOutputManager.cs](https://github.com/anotherlab/UsbSerialForAndroid/blob/master/UsbSerialForAndroid/Extensions/SerialInputOutputManager.cs).  Setting the baud rate in that class is only used when you open the port.

**Comment by gokhangocmen94** [comment]
I can't use SetParameters() method. It is not being support.
Aren't there any way for changing BaudRate?

**Comment by anotherlab** [comment]
I don't understand what you mean by "I can't use SetParameters() method. It is not being support."

The SetParameters() method is called by the open methods.

Why can't you set the baud rate before you open the port?

**Comment by gokhangocmen94** [comment]
How Should I use SetParameters() method. When I use, I have a Syntax error.

I set baud rate 300, before I open the port. But I want to change baud rate to 1200, after read any character by using 300 baud rate. My issue is this: How Can I change baud rate?

**Comment by anotherlab** [comment]
Compile time error or runtime error?  Please be more specific with the details.  

For an example on how to call SetParameters(), look at it how [it's called in the code](https://github.com/anotherlab/UsbSerialForAndroid/blob/master/UsbSerialForAndroid/Extensions/SerialInputOutputManager.cs#L81).

**Comment by gokhangocmen94** [comment]
That is Run Time Error. Baud Rate is changing with SetParameters(), But UpdateReceiveData() function is not working after Baud Rate change... Have you any idea about this?

**Comment by gokhangocmen94** [comment]
I changed BaudRate successfully. Thank you very much

```
private void ReadAButton_Click(object sender, EventArgs e)
        {
            readMode = 0;
            WriteData(string0);
        }
private void ReadBButton_Click(object sender, EventArgs e)
        {
            readMode = 1;
            WriteData(string1);
        }
void UpdateReceivedData(byte[] data)
        {
            if (readMode == 0)
            {
                port.SetParameters(300, 8, STOPBITS_VALUE, PARITY_VALUE);
            }
            else if (readMode == 1)
            {
                port.SetParameters(1200, 8, STOPBITS_VALUE, PARITY_VALUE);
            }
         }
```

**Comment by gokhangocmen94** [comment]
I changed BaudRate successfully. Thank you very much

```
private void ReadAButton_Click(object sender, EventArgs e)
        {
            readMode = 0;
            WriteData(string0);
        }
private void ReadBButton_Click(object sender, EventArgs e)
        {
            readMode = 1;
            WriteData(string1);
        }
void UpdateReceivedData(byte[] data)
        {
            if (readMode == 0)
            {
                port.SetParameters(300, 8, STOPBITS_VALUE, PARITY_VALUE);
            }
            else if (readMode == 1)
            {
                port.SetParameters(1200, 8, STOPBITS_VALUE, PARITY_VALUE);
            }
         }
```

**Comment by gokhangocmen94** [comment]
aaaaaaaaaaaaa
