### ISSUE TITLE
Error writing/reading data

### ISSUE THREAD

**Issue by X-627** [anotherlab/UsbSerialForAndroid#11]
I am trying to run the example code on in UsbSerialForAndroid and if I try to read or write anything the app crashes
It does detect the device which is using CdcAcmSerialDriver (STM32 Nucleo)
Initially on connect it will give a false result which is always 64 bytes in length and has false values 

Read 64 bytes: 
0x00000000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0x00000030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

However when I try to write to it I am greeted by this error message:

`Java.IO.IOException: Exception of type 'Java.IO.IOException' was thrown.
  at Hoho.Android.UsbSerial.Driver.CdcAcmSerialDriver+CdcAcmSerialPort.Write (System.Byte[] src, System.Int32 timeoutMillis) [0x000d3] in <76b96e7b0d204cfe93490d0d3b6dfa0a>:0 
  at UsbSerialExampleApp.SerialConsoleActivity.WriteData (System.Byte[] data) [0x0002e] in <ed01142b0128460fae48f975e230055f>:0 
  --- End of managed Java.IO.IOException stack trace ---
java.io.IOException: Error writing 46 bytes at offset 0 length=46
	at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
	at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
	at android.view.View.performClick(View.java:6306)
	at android.widget.TextView.performClick(TextView.java:11201)
	at android.view.View$PerformClick.run(View.java:23962)`

What might be the issue? As I have Tested it with Serial USB Terminal it works fine

**Comment by anotherlab** [comment]
I don't know if that driver will work with a Nucleo.  STMicroelectronics wrote a STM32 driver for the Java source of the library.  It's not included in [mik3y's library](https://github.com/mik3y/usb-serial-for-android), but STM has documented it [here](https://github.com/STMicroelectronics/STMCD_Android_BasicGpioDemo) and the source code is [here](https://github.com/STMicroelectronics/STMCD_Android_BasicGpioDemo/blob/master/AndroidBasicGpioDemo/app/src/main/java/com/hoho/android/usbserial/driver/STM32SerialDriver.java).  It shouldn't be too difficult to port that code from Java to C#.

**Comment by nwestfall** [comment]
@X-627 I do not have the device you are using, but I did port the source code for the driver over mentioned in @anotherlab comment.

Please try out the code in PR #12 and let me know how it works.

**Comment by anotherlab** [comment]
And has been brought [to the attention](https://groups.google.com/forum/#!topic/stm32_en/0J30h0BmOzY) of the STM32 developer,

**Comment by X-627** [comment]
I tested the driver, had to add the device to the table in order for it to be found, which is fine. However now I recieve all zeros as bytes no matter what I right. 
Example below:

Read 1 bytes: 
0x00000000 00                                              .
Read 1 bytes: 
0x00000000 00                                              .
Read 14 bytes: 
0x00000000 00 00 00 00 00 00 00 00 00 00 00 00 00 00       ..............
Read 4 bytes: 
0x00000000 00 00 00 00                                     ....
Read 2 bytes: 
0x00000000 00 00                                           ..
Read 3 bytes: 
0x00000000 00 00 00                                        ...
Read 3 bytes: 
0x00000000 00 00 00                                        ...
Read 4 bytes: 
0x00000000 00 00 00 00                                     ....
Read 4 bytes: 
0x00000000 00 00 00 00                                     ....
Read 3 bytes: 
0x00000000 00 00 00                                        ...
Read 2 bytes: 
0x00000000 00 00                                           ..
Read 2 bytes: 
0x00000000 00 00                                           ..
Read 2 bytes:

Any suggestions?

**Comment by anotherlab** [comment]
I don't have the device, but I would put a breakpoint in the Read() method in [STM32SerialDriver.cs](https://github.com/anotherlab/UsbSerialForAndroid/blob/master/UsbSerialForAndroid/driver/STM32SerialDriver.cs) and check what is in mReadBuffer right after this line
`numBytesRead = mConnection.BulkTransfer(mReadEndpoint, mReadBuffer, readAmt, timeoutMillis)`

That would tell you if the data was being pulled in correctly from the device.

**Comment by X-627** [comment]
What do use to debug and connect to serial at the same time? I am currently using a tablet with a single port and would prefer a solution for it. However I have jetson dev kit that supports android if that's the way to go

**Comment by anotherlab** [comment]
We used a tablet that has multiple USB ports, allowing a standard USB ADB connection for debugging and using the other USB port for connecting to the devices.  With a single port, your options will be limited.  I would try to get the ADB connection over Wi-Fi.  The Stackover flow post [Run/install/debug Android applications over Wi-Fi?](https://stackoverflow.com/questions/4893953/run-install-debug-android-applications-over-wi-fi) has a few suggestions for getting ADB to work over Wi-Fi.

**Comment by anotherlab** [comment]
Another option would be to get a decent powered USB hub.  That "should" work, but make sure it's a decent.  Cheap USB hubs can introduce latency issues.
