### ISSUE TITLE
Read timeout is not appling

### ISSUE THREAD

**Issue by antonad** [anotherlab/UsbSerialForAndroid#13]
I am using  FtdiSerial device on android 5.

When I am trying to read data, timeout is not applied.
My code works fine only if I will put thread. sleep (1000) before reading.

                DateTime now = DateTime.Now;
                int cnt = m_Port.Read(data, 5000);
                TimeSpan s = DateTime.Now - now;
as result 
s < 10 ms.
cnt = 0

**Comment by anotherlab** [comment]
Are you sure that there is data in the buffer when you make the read call?  Are you making a single call to Rad() or are you in a loop?

The timeout in Read() is used in mConnection.BulkTransfer(), which an Android API call to [USBDeviceConnection.BulkTransfer()](https://developer.android.com/reference/android/hardware/usb/UsbDeviceConnection#bulkTransfer(android.hardware.usb.UsbEndpoint,%20byte[],%20int,%20int)).

**Comment by antonad** [comment]
> Are you sure that there is data in the buffer when you make the read call? Are you making a single call to Rad() or are you in a loop?
Device I am working with will reply in 1 sec approximatelly. There is now data in port when I am starting reading, but I will come during wait interval.

I suggest the problem is in device type. As I see  Ftdi sends 2 additional bytes. may be an application don't wait because of this prefix?

As result I have made my app working with next way:
`
        byte[] Read(int count)
        {
            byte[] reply = new byte[count];
            int readCount = 0;
            int retry = 10;
            while (readCount < count)
            {
                byte[] data = new byte[count + 2];
                int cnt = m_Port.Read(data, 150);
                if (cnt == 0)
                {
                    if (--retry == 0)
                        throw new Exception("No reply");
                    Thread.Sleep(150);
                }
                for (int i = 0; i < cnt; i++)
                    reply[readCount++] = data[i];
            }
            return reply;
        }

`
