### ISSUE TITLE
Debugging on device impossible : android minimal version

### ISSUE THREAD

**Issue by bizulk** [anotherlab/UsbSerialForAndroid#14]
Hello !
I downloaded project but can deploy or debug on any device (tablet or emulator).
It says that I have to change "android minimal version".
I Have various devices they are based on Android 7.1 or 8.1.
I checked the manifest and set as follow : 
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.PandaIHM">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="27" />
    <application android:label="PandaIHM.Android"></application>
</manifest>
```
But it is completely ignored, why ?
the target SDK is 8.1

**Comment by hamidrezaazizyianpour** [comment]
hi
I have exactly the same problem.

**Comment by anotherlab** [comment]
What was the exact error that you received?  Was it with the library or the sample app?  And with which version of Visual Studio?  Which Android platform SDKs do you have installed?  We are using this library on various Android tablets, running Android 5.1 to 8.1

**Comment by bizulk** [comment]
Hello !

Here are more infos about the env : 
I opened the solution in your repo and try to launch **UsbSerialExampleApp**.
The button "start" or "launch" used for debugging is not listing any of the available devices (API 23 to 27, various arch ARM/x86).
If I scrool options from this button  there is a list "unsupported device" that contains all the one I have, and one the bottom of this list I have an command '"change android minimal version". This command opened the manifest, but there is nothing there that has to be changed, from my opinion, and tries.

About the IDE and SDK : 

> Microsoft Visual Studio Community 2017 
> Version 15.9.6
> VisualStudio.15.Release/15.9.6+28307.344
> Microsoft .NET Framework
> Version 4.7.03056
> 
> Version installée : Community
> 
> Visual C++ 2017   00369-60000-00001-AA470
> Microsoft Visual C++ 2017
> 
> ASP.NET and Web Tools 2017   15.9.04012.0
> ASP.NET and Web Tools 2017
> 
> Assistants Microsoft Visual C++   1.0
> Assistants Microsoft Visual C++
> 
> Azure App Service Tools v3.0.0   15.9.03024.0
> Azure App Service Tools v3.0.0
> 
> Common Azure Tools   1.10
> Fournit des services courants utilisables par Microsoft Azure Mobile Services et Microsoft Azure Tools.
> 
> Cookiecutter   15.9.18254.1
> Fournit des outils pour rechercher, instancier et personnaliser des modèles au format cookiecutter.
> 
> Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
> Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
> 
> Extension ResourcePackage   1.0
> Informations détaillées sur l'extension Visual Studio ResourcePackage
> 
> Extension ResourcePackage   1.0
> Informations détaillées sur l'extension Visual Studio ResourcePackage
> 
> Gestionnaire de package NuGet   4.6.0
> Gestionnaire de package NuGet dans Visual Studio. Pour plus d'informations sur NuGet, consultez la page http://docs.nuget.org/.
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> JavaScript UWP Project System   2.0
> JavaScript UWP Project System
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools pour Microsoft Visual Studio 2017 - v2.9.10730.2
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> MLGen Package Extension   1.0
> MLGen Package Visual Studio Extension Detailed Info
> 
> Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
> Support for debugging Mono processes with Visual Studio.
> 
> Outils C#   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
> Composants C# utilisés dans l'IDE. En fonction de votre type de projet et de vos paramètres, une autre version du compilateur peut être utilisée.
> 
> Outils TypeScript   15.9.20918.2001
> Outils TypeScript pour Microsoft Visual Studio
> 
> Outils Visual Basic   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
> Composants Visual Basic utilisés dans l'IDE. En fonction de votre type de projet et de vos paramètres, une autre version du compilateur peut être utilisée.
> 
> Package hôte de l'adaptateur de débogage de Visual Studio Code   1.0
> Couche d'interopérabilité pour l'hébergement d'adaptateurs de débogage Visual Studio Code dans Visual Studio
> 
> Package Microsoft Visual Studio VC   1.0
> Package Microsoft Visual Studio VC
> 
> Package Outils Application Insights pour Visual Studio   8.14.11009.1
> Outils Application Insights pour Visual Studio
> 
> ProjectServicesPackage Extension   1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> Python   15.9.18254.1
> Fournit IntelliSense, des projets, des modèles, le débogage, des fenêtres interactives et du support pour les développeurs Python.
> 
> Python - Prise en charge Django   15.9.18254.1
> Fournit des modèles et une intégration pour le framework web Django.
> 
> Python - Prise en charge du profilage   15.9.18254.1
> Prise en charge du profilage pour les projets Python.
> 
> Python - Prise en charge IronPython   15.9.18254.1
> Fournit des modèles et une intégration pour les projets basés sur IronPython.
> 
> Service de langage JavaScript   2.0
> Service de langage JavaScript
> 
> Visual C++ pour le développement mobile multiplateforme   15.0.28107.00
> Visual C++ pour le développement mobile multiplateforme
> 
> Visual F# Tools 10.2 pour F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
> Microsoft Visual F# Tools 10.2 pour F# 4.5
> 
> Visual Studio Tools pour les applications Windows universelles   15.0.28307.208
> Visual Studio Tools pour les applications Windows universelles vous permet de créer une expérience d'application universelle unique que vous pouvez retrouver sur tous les appareils exécutant Windows 10 : téléphones, tablettes, PC, etc. Il inclut le Kit de développement logiciel (SDK) Microsoft Windows 10.
> 
> Visual C++ pour le développement mobile multiplateforme (iOS)   15.0.28016.00
> Visual C++ pour le développement mobile multiplateforme (iOS)
> 
> VisualStudio.Mac   1.0
> Mac Extension for Visual Studio
> 
> Xamarin   4.12.3.79 (d15-9@260fa6a34)
> Extension Visual Studio permettant de développer pour Xamarin.iOS et Xamarin.Android.
> 
> Xamarin Designer   4.16.13 (45a16efd4)
> Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
> 
> Xamarin Templates   1.1.128 (6f5ebb2)
> Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
> 
> Xamarin.Android SDK   9.1.5.0 (HEAD/4b951a3e7)
> Xamarin.Android Reference Assemblies and MSBuild support.
> 
> Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
> Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by anotherlab** [comment]
If the minimum SDK that you have installed is 23 (6.0), then I think you have two options.  Install SDK 21 or change the target framework for the sample app to 23.
