### ISSUE TITLE
Build error: Java.Interop version conflicts

### ISSUE THREAD

**Issue by ygoe** [anotherlab/UsbSerialForAndroid#22]
First, I've downloaded the entire repository and built it with VS 2022 17.2.0 Preview 2.1. It did build and I could deploy the sample app on my Android phone and receive data from a microcontroller.

So the next step was to just use the library and add it to a new app. I started with a .NET MAUI app (which also worked as is) and tried to integrate the device listing and simple communication code into the default page that's created there. I added the library project from your solution to my solution and also added a project reference to it.

But now my build fails with some version conflicts of Java.Interop. It sees versions 0.1.0.0 and 0.2.0.2. I have no idea what these are. Can you please explain how this library should be used? There's no NuGet package so I have to find my own ways.

**Comment by anotherlab** [comment]
@ygoe This library has not been built for or tested with MAUI Android.

The sample project has commented code on how to use the library with regards to using it.

**Comment by ygoe** [comment]
I ended up creating a new MAUI class library project and copied all your source files into my project. That works. So I guess a NuGet package wouldn't be helpful anyway. I'm still new to MAUI (and Xamarin) so I don't know the best practices here.
