### ISSUE TITLE
CdcAcmSerialDriver cannot be instantiated from ProbeDevice due to no matching constructor signature

### ISSUE THREAD

**Issue by andrewhaighcell** [anotherlab/UsbSerialForAndroid#26]
Hi,
Whilst trying out the driver with an Arduino device, I found that it cannot correctly create a suitable driver instance of the CdcAcmSerialDriver class. 

This is because there is no suitable matching function prototype to be called from the ProbeDevice():
https://github.com/anotherlab/UsbSerialForAndroid/blob/main/UsbSerialForAndroid/driver/UsbSerialProber.cs#L94
...
driver = (IUsbSerialDriver)Activator.CreateInstance(driverClass, new System.Object[] {usbDevice});
...

**Does not match the constructor signature** in:
https://github.com/anotherlab/UsbSerialForAndroid/blob/main/UsbSerialForAndroid/driver/CdcAcmSerialDriver.cs#L34

 public CdcAcmSerialDriver(UsbDevice device, **bool? enableAsyncReads = null**)
        {

My workaround for now was to add a constructor with a single argument and just default enableAsyncReads=false; Obviously this could do with something more sophisticated for a proper fix...

 public CdcAcmSerialDriver(UsbDevice device)
        {
... 

I believe the original Java code does not have the same problem, because it only accepts a single UsbDevice argument for the ctor:
https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/UsbSerialProber.java#L82
https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java#L38

**Comment by pravincar** [comment]
@andrewhaighcell I had created the PR to add the optional enableAsyncReads parameter without realizing that this driver is also instantiated via reflection. Adding a new constructor seems like the best way forward. Can you open a PR with your change?

**Comment by andrewhaighcell** [comment]
I will try and sort that out over the weekend yes.

Thanks,
Andrew Haigh

**Comment by andrewhaighcell** [comment]
PR now raised here: https://github.com/anotherlab/UsbSerialForAndroid/pull/27

**Comment by andrewhaighcell** [comment]
@pravincar Hi, its not urgent but perhaps you would like to roll this change into the mainline? Thanks!

**Comment by andrewhaighcell** [comment]
Maybe @anotherlab might pull this in? Thanks!

**Comment by andrewhaighcell** [comment]
My fix has now been merged so this can be closed.
