### ISSUE TITLE
Porting to .NET MAUI?

### ISSUE THREAD

**Issue by ndt1896** [anotherlab/UsbSerialForAndroid#28]
I'm new to Xamarin, and also recently learned about .NET MAUI.  I'd like to open a discussion about what would be necessary to port this to a MAUI project.  For all I know, it might be possible to consume this library directly in a MAUI project, but am not sure how.  Any thoughts or ideas on the practicality or steps to port this project?  Looking forward to any ideas or advice.

**Comment by anotherlab** [comment]
This project could be consumed on the Android platform with MAUI, but it wouldn't work for iOS or Windows.

**Comment by ndt1896** [comment]
Thanks for the response.  Consuming this project for the Android part of a larger MAUI project looks like the way to go.
