### ISSUE TITLE
How Can I Call UsbDevice.ManufacturerName variable?

### ISSUE THREAD

**Issue by gokhangocmen94** [anotherlab/UsbSerialForAndroid#4]
Hello.
I want to call connected device's manufacturer name. But, When I call like this "port.GetDriver()).GetDevice().ManufacturerName" , I have an runtime error.

How Should I call this variable?

**Comment by anotherlab** [comment]
The ManufacturerName property of the UsbDevice object should be populated by Android.  Did you check to see if the property was set to null?  According to the [documentation](https://developer.android.com/reference/android/hardware/usb/UsbDevice.html#getManufacturerName()), null is an acceptable value for that property.
