### ISSUE TITLE
921600 bauds support ?

### ISSUE THREAD

**Issue by ThierryDFR** [anotherlab/UsbSerialForAndroid#43]
Hi and thanks for your library.

I use a CH340e and
In your code I see the baud rate supported : 
int[] baud = new int[]
                {
                    2400, 0xd901, 0x0038, 4800, 0x6402,
                    0x001f, 9600, 0xb202, 0x0013, 19200, 0xd902, 0x000d, 38400,
                    0x6403, 0x000a, 115200, 0xcc03, 0x0008
                };

But I want use a higger baud rate of 921 600 bauds.
It is possible with your library ?
if it is possible what is the good values for 921600 to complete the int[] baud value accepted ?

**Comment by ThierryDFR** [comment]
Hi Chirs,
Many many thanls for your help.
That's work perfectly !!!
I send to you all information for update your library ....
I have translate the "setBaudRate" java function in c# from your link (without "ControlOut" function for only extract Val1 and Val2 data).
I have tested some values and that's works perfectly except above 921600 (My USB phone ? Cables ? My ESP32-CAM ?).
For 1500000 bauds, ESP32-cam hang and reboot sometimes.
For 2000000 bauds, dialogue is bad all the time.

This is the complete list of all value for all baud rates managed by CH340 with product ID 0x7523 (table.AddProduct(0x1A86, 0x7523, typeof(Ch34xSerialDriver)); // ESP32cam programmer), except : 134.5 bauds : 

`int[] baud = new int[]
{
   50, 0x1680, 0x0024, 75, 0x6480, 0x0018, 100, 0x8B80, 0x0012, 110, 0x9580, 0x00B4, 
  150, 0xB280, 0x000C, 300, 0xD980, 0x0006, 600, 0x6481, 0x0018, 900, 0x9881, 0x0010,
  1200, 0xB281, 0x000C, 1800, 0xCC81, 0x0008, 2400, 0xD981, 0x0006, 3600, 0x3082, 0x0020,
  4800, 0x6482, 0x0018, 9600, 0xB282, 0x000C, 14400, 0xCC82, 0x0008, 19200, 0xD982, 0x0006,
  33600, 0x4D83, 0x00D3, 38400, 0x6483, 0x0018, 56000, 0x9583, 0x0018, 57600, 0x9883, 0x0010,
  76800, 0xB283, 0x000C, 115200, 0xCC83, 0x0008, 128000, 0xD183, 0x003B, 153600, 0xD983, 0x0006,
  230400, 0xE683, 0x0004, 460800, 0xF383, 0x0002, 921600, 0xF387, 0x0000, 1500000, 0xFC83, 0x0003,
  2000000, 0xFD83, 0x0002
};`

If you see value for 115200 bauds for example, the value is not the same that your actual value, after somes tests the connection is more stable with this new values 115200 bauds.

I send to you the translate code of the new java "setBaudRate" (without "ControlOut" function for only extract Val1 and Val2 data) : 

`private struct Values
        {
            public int Baud;
            public int val1;
            public int val2;
            public long factor;
            public long divisor;
            public override String ToString() { 
                return Baud + "\t\t" 
                    + " 0x" + val1.ToString("X4") + "\t" 
                    + " 0x" + val2.ToString("X4") + "\t"
                    + " 0x" + factor.ToString("X4") + "\t" 
                    + " 0x" + divisor.ToString("X4"); }
        }
        private Values setBaudRate(int baudRate)
        {
            Values Val = new Values(); long factor; long divisor; bool DEBUG = false;
            if (baudRate == 921600) { divisor = 7; factor = 0xf300; } 
            else {
                           long BAUDBASE_FACTOR = 1532620800; int BAUDBASE_DIVMAX = 3;
                           if(DEBUG && (baudRate & (3<<29)) == (1<<29)) { baudRate &= ~(1 << 29); } // for testing purpose bypass dedicated baud rate handling
                factor = BAUDBASE_FACTOR / baudRate;
                           divisor = BAUDBASE_DIVMAX;
                           while ((factor > 0xfff0) && divisor > 0) { factor >>= 3; divisor--; }
                if (factor > 0xfff0) { throw new Exception("Unsupported baud rate: " + baudRate); }
                factor = 0x10000 - factor;
                    }
                    divisor |= 0x0080; // else ch341a waits until buffer full
            Val.val1 = (int)((factor & 0xff00) | divisor);
            Val.val2 = (int)(factor & 0xff);
            Val.factor = factor;
            Val.divisor = divisor;
            Val.Baud = baudRate;
            return Val;
             }
`

for usage : textBox1.Text = textBox1.Text + "\r\n" + setBaudRate(115200).ToString();



Many thanks, your library is perfect now with this new values !!

**Comment by anotherlab** [comment]
I just merged your PR into main. Thank you!
