### ISSUE TITLE
NuGet package distribution

### ISSUE THREAD

**Issue by Deilan** [anotherlab/UsbSerialForAndroid#9]
Please distribute a library via NuGet.

**Comment by EliseJoffre** [comment]
There is a Nuget Distribution so ?

**Comment by Deilan** [comment]
@EliseJoffre so maybe provide a link to it in repo readme then?

**Comment by ygoe** [comment]
@EliseJoffre @anotherlab There's no NuGet package available for this library. If the nuget.org search is somehow blind, please let me know where I can find it.
